fetch:
	# @todo lambda function
	wget https://packagist.org/packages/list.json?vendor=contributte -o contributte.json
	wget https://packagist.org/packages/list.json?vendor=apitte -o apitte.json
	wget https://packagist.org/packages/list.json?vendor=nettrine -o nettrine.json

install:
	composer install
