terraform import github_repository.digitalpaint digitalpaint || true
terraform import github_repository.rankface rankface || true
terraform import github_repository.gopay gopay || true
terraform import github_repository.kleinphp-smartyphp kleinphp-smartyphp || true
terraform import github_repository.mobilni-platby mobilni-platby || true
terraform import github_repository.codeception codeception || true
terraform import github_repository.newrelic newrelic || true
terraform import github_repository.pdf pdf || true
terraform import github_repository.menu-control menu-control || true
terraform import github_repository.thumbator thumbator || true
terraform import github_repository.newrelic-tracy newrelic-tracy || true
terraform import github_repository.reCAPTCHA reCAPTCHA || true
terraform import github_repository.kleinphp-latte kleinphp-latte || true
terraform import github_repository.planette-play-site planette-play-site || true
terraform import github_repository.social social || true
terraform import github_repository.forms-controls forms-controls || true
terraform import github_repository.latte-email latte-email || true
terraform import github_repository.tester-skeleton tester-skeleton || true
terraform import github_repository.latte-formatter latte-formatter || true
terraform import github_repository.dummy-events dummy-events || true
terraform import github_repository.gopay-inline gopay-inline || true
terraform import github_repository.imap imap || true
terraform import github_repository.cli-http cli-http || true
terraform import github_repository.ghpage ghpage || true
terraform import github_repository.latte-parsedown latte-parsedown || true
terraform import github_repository.latte-parsedown-extra latte-parsedown-extra || true
terraform import github_repository.gopay-api gopay-api || true
terraform import github_repository.uniparser uniparser || true
terraform import github_repository.simple-blogger simple-blogger || true
terraform import github_repository.ftpdeployer ftpdeployer || true
terraform import github_repository.nextras-orm-generator nextras-orm-generator || true
terraform import github_repository.live-form-validation live-form-validation || true
terraform import github_repository.forms-wizard forms-wizard || true
terraform import github_repository.forms-multiplier forms-multiplier || true
terraform import github_repository.ntdb ntdb || true
terraform import github_repository.thepay-api thepay-api || true
terraform import github_repository.thepay thepay || true
terraform import github_repository.componette-site componette-site || true
terraform import github_repository.platte platte || true
terraform import github_repository.pidic pidic || true
terraform import github_repository.cookbook cookbook || true
terraform import github_repository.gopay-simple gopay-simple || true
terraform import github_repository.blogette blogette || true
terraform import github_repository.datagrid datagrid || true
terraform import github_repository.webhosting-tools webhosting-tools || true
terraform import github_repository.benchmarks benchmarks || true
terraform import github_repository.image-storage image-storage || true
terraform import github_repository.api-router api-router || true
terraform import github_repository.api-docu api-docu || true
terraform import github_repository.nusoap nusoap || true
terraform import github_repository.invoice invoice || true
terraform import github_repository.datagrid-nette-database-data-source datagrid-nette-database-data-source || true
terraform import github_repository.wordcha wordcha || true
terraform import github_repository.fileupload fileupload || true
terraform import github_repository.seznamcaptcha seznamcaptcha || true
terraform import github_repository.guzzlette guzzlette || true
terraform import github_repository.fly-response fly-response || true
terraform import github_repository.componette-dockerfiles componette-dockerfiles || true
terraform import github_repository.doctrine-extensions-atlantic18 doctrine-extensions-atlantic18 || true
terraform import github_repository.service-autoloader service-autoloader || true
terraform import github_repository.nextras-criteria nextras-criteria || true
terraform import github_repository.model-specification model-specification || true
terraform import github_repository.nextras-orm-events nextras-orm-events || true
terraform import github_repository.dockerfiles dockerfiles || true
terraform import github_repository.utils utils || true
terraform import github_repository.webmaster-tools webmaster-tools || true
terraform import github_repository.application application || true
terraform import github_repository.nextras-orm-query-object nextras-orm-query-object || true
terraform import github_repository.microapi microapi || true
terraform import github_repository.console console || true
terraform import github_repository.event-dispatcher event-dispatcher || true
terraform import github_repository.dev dev || true
terraform import github_repository.latte latte || true
terraform import github_repository.security security || true
terraform import github_repository.mail mail || true
terraform import github_repository.api api || true
terraform import github_repository.logging logging || true
terraform import github_repository.http http || true
terraform import github_repository.cache cache || true
terraform import github_repository.dataql dataql || true
terraform import github_repository.di di || true
terraform import github_repository.database database || true
terraform import github_repository.bootstrap bootstrap || true
terraform import github_repository.psr6-caching psr6-caching || true
terraform import github_repository.psr7-http-message psr7-http-message || true
terraform import github_repository.neonizer neonizer || true
terraform import github_repository.middlewares middlewares || true
terraform import github_repository.forms forms || true
terraform import github_repository.playground playground || true
terraform import github_repository.event-application-bridge event-application-bridge || true
terraform import github_repository.event-security-bridge event-security-bridge || true
terraform import github_repository.event-bridges event-bridges || true
terraform import github_repository.webpack webpack || true
terraform import github_repository.doctrine-orm doctrine-orm || true
terraform import github_repository.doctrine-migrations doctrine-migrations || true
terraform import github_repository.tracy tracy || true
terraform import github_repository.doctrine-dbal doctrine-dbal || true
terraform import github_repository.model model || true
terraform import github_repository.psr11-container-interface psr11-container-interface || true
terraform import github_repository.rabbitmq rabbitmq || true
terraform import github_repository.planette-site planette-site || true
terraform import github_repository.commits-site commits-site || true
terraform import github_repository.api-router-skeleton api-router-skeleton || true
terraform import github_repository.phpdoc phpdoc || true
terraform import github_repository.apitte-skeleton apitte-skeleton || true
terraform import github_repository.contributte contributte || true
terraform import github_repository.doctrine-fixtures doctrine-fixtures || true
terraform import github_repository.facebook facebook || true
terraform import github_repository.apitte apitte || true
terraform import github_repository.apitte-negotiation apitte-negotiation || true
terraform import github_repository.apitte-openapi apitte-openapi || true
terraform import github_repository.apitte-middlewares apitte-middlewares || true
terraform import github_repository.apitte-events apitte-events || true
terraform import github_repository.apitte-mapping apitte-mapping || true
terraform import github_repository.apitte-fullstack apitte-fullstack || true
terraform import github_repository.apitte-debug apitte-debug || true
terraform import github_repository.doctrine-annotations doctrine-annotations || true
terraform import github_repository.apitte-presenter apitte-presenter || true
terraform import github_repository.apitte-console apitte-console || true
terraform import github_repository.fio fio || true
terraform import github_repository.console-extra console-extra || true
terraform import github_repository.datagrid-elasticsearch-data-source datagrid-elasticsearch-data-source || true
terraform import github_repository.doctrine-cache doctrine-cache || true
terraform import github_repository.anabelle anabelle || true
terraform import github_repository.scheduler scheduler || true
terraform import github_repository.mailing mailing || true
terraform import github_repository.micro-skeleton micro-skeleton || true
terraform import github_repository.starter-skeleton starter-skeleton || true
terraform import github_repository.console-skeleton console-skeleton || true
terraform import github_repository.advisories advisories || true
terraform import github_repository.phalboot phalboot || true
terraform import github_repository.notefw notefw || true
terraform import github_repository.webpack-skeleton webpack-skeleton || true
terraform import github_repository.event-dispatcher-extra event-dispatcher-extra || true
terraform import github_repository.contributte-site contributte-site || true
terraform import github_repository.elasticsearch elasticsearch || true
terraform import github_repository.flysystem flysystem || true
terraform import github_repository.hydrator hydrator || true
terraform import github_repository.webapp-skeleton webapp-skeleton || true
terraform import github_repository.oauth2-client oauth2-client || true
terraform import github_repository.jsonrpc jsonrpc || true
terraform import github_repository.monolog monolog || true
terraform import github_repository.php-hostinfo php-hostinfo || true
terraform import github_repository.redis redis || true
terraform import github_repository.replacus replacus || true
terraform import github_repository.czech-post czech-post || true
terraform import github_repository.gosms gosms || true
terraform import github_repository.translation translation || true
terraform import github_repository.planette-micro-site planette-micro-site || true
terraform import github_repository.dag dag || true
terraform import github_repository.comgate comgate || true
terraform import github_repository.eet eet || true
terraform import github_repository.doctrine-extensions-beberlei doctrine-extensions-beberlei || true
terraform import github_repository.doctrine-extensions-knplabs doctrine-extensions-knplabs || true
terraform import github_repository.doctrine-extensions-oroinc doctrine-extensions-oroinc || true
terraform import github_repository.validator validator || true
terraform import github_repository.bare bare || true
terraform import github_repository.code-checker code-checker || true
terraform import github_repository.forms-bootstrap forms-bootstrap || true
terraform import github_repository.doctrine-odm doctrine-odm || true
terraform import github_repository.doctrine-mongodb doctrine-mongodb || true
terraform import github_repository.oauth2-server oauth2-server || true
terraform import github_repository.embedded-skeleton embedded-skeleton || true
terraform import github_repository.qa qa || true
terraform import github_repository.componette-design componette-design || true
terraform import github_repository.tester tester || true
terraform import github_repository.ui ui || true
terraform import github_repository.aop aop || true
terraform import github_repository.elastica elastica || true
terraform import github_repository.doctrine-gedmo doctrine-gedmo || true
terraform import github_repository.imagist imagist || true
terraform import github_repository._github .github || true
terraform import github_repository.code-rules code-rules || true
terraform import github_repository.fx-skeleton fx-skeleton || true
terraform import github_repository.firewall firewall || true
terraform import github_repository.doctrine-extra-skeleton doctrine-extra-skeleton || true
terraform import github_repository.gettext gettext || true
terraform import github_repository.apitte-core apitte-core || true
terraform import github_repository.paginator-control paginator-control || true
terraform import github_repository.datagrid-skeleton datagrid-skeleton || true
terraform import github_repository.gui-skeleton gui-skeleton || true
terraform import github_repository.nella nella || true
terraform import github_repository.payments-skeleton payments-skeleton || true
terraform import github_repository.nella-skeleton nella-skeleton || true
terraform import github_repository.sentry sentry || true
terraform import github_repository.sentry-skeleton sentry-skeleton || true
terraform import github_repository.crafter crafter || true
terraform import github_repository.phpless phpless || true
terraform import github_repository.doctrine-skeleton doctrine-skeleton || true
terraform import github_repository.bus bus || true
terraform import github_repository.vite vite || true
terraform import github_repository.vite-skeleton vite-skeleton || true
terraform import github_repository.ui-skeleton ui-skeleton || true
terraform import github_repository.lambdas lambdas || true
terraform import github_repository.instahost instahost || true
terraform import github_repository.messenger messenger || true
terraform import github_repository.framex framex || true
terraform import github_repository.messenger-skeleton messenger-skeleton || true
terraform import github_repository.phpunit phpunit || true
terraform import github_repository.phpstan phpstan || true
terraform import github_repository.doctrine doctrine || true
terraform import github_repository.doctrine-extra doctrine-extra || true
terraform import github_repository.framex-skeleton framex-skeleton || true
terraform import github_repository.kernel kernel || true
terraform import github_repository.openapi openapi || true
terraform import github_repository.ddd-skeleton ddd-skeleton || true
terraform import github_repository.demo-frankenphp demo-frankenphp || true
terraform import github_repository.api-skeleton api-skeleton || true
terraform import github_repository.all all || true
terraform import github_repository.webdata webdata || true
terraform import github_repository.doctrine-project doctrine-project || true
terraform import github_repository.demo-typesense demo-typesense || true
terraform import github_repository.turnstile turnstile || true