name: "Std 001 - EditorConfig"

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository'
        required: true

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.inputs.repository }}"

      - name: Extract branch name
        run: echo "::set-output name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/})"
        id: extractor

      - name: Make changes
        run: |
          curl https://raw.githubusercontent.com/${{ github.repository }}/${{ steps.extractor.outputs.BRANCH_NAME }}/std/001-editorconfig/editorconfig --output .editorconfig

      - name: Create PR
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.CONTRIBUTTE_PAT }}
          title: "Std 001 - EditorConfig"
          branch: "create-pull-request/std-001-editorconfig"
          commit-message: "Std: EditorConfig"
