name: "Std 003 - funding"

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository'
        required: true

env:
  std: "std/003-funding"
  branchName: "feature/std-003-funding"
  commitMessage: "Std [003]: funding"

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.inputs.repository }}

      - name: Prepare variables
        run: echo "::set-output name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/})"
        id: variables

      - name: Make changes
        run: |
          mkdir -p .github || true
          curl https://raw.githubusercontent.com/${{ github.repository }}/${{ steps.variables.outputs.BRANCH_NAME }}/${{ env.std }}/FUNDING.yml --output .github/FUNDING.yml

      - name: Create PR
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.CONTRIBUTTE_PAT }}
          title: ${{ github.github.workflow }}
          branch: ${{ env.branchName }}
          commit-message: ${{ env.commitMessage }}
          body: |
            Contributte standard. 👨🏻‍💻
            See more at [contributte/contributte](https://github.com/contributte/contributte).
